# -*- coding: utf-8 -*-
"""LAB 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Okj1Iw2Eg1JQ9sqN1hth07lTGMN1J9be
"""

!pip install -q -U google-genai gradio

from google import genai
from getpass import getpass
import os
import gradio as gr

os.environ["GEMINI_API_KEY"] = getpass("Enter your Gemini API Key: ")
client = genai.Client()

def analyze_email(file):
    if file is None:
        return "Please upload an email chain text file."

    with open(file.name, "r", encoding="utf-8") as f:
        email_chain = f.read()

    prompt = f"""
You are an Email Assistant for a startup founder.
Read the email chain and return:
1. Summary
2. Key people
3. Actionable tasks table: Task | Priority | Reason | Deadline | Follow-up
4. Overall next step
Use High, Medium, or Low priority based on urgency, deadline, investor/customer impact, and business risk.

Email chain:
{email_chain}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text

with gr.Blocks() as app:
    gr.Markdown("# Email Assistant for a Startup Founder")
    gr.Markdown("Upload an email chain text file to get summary, tasks, priorities, and follow-up suggestions.")

    email_file = gr.File(label="Upload Email Chain Text File", file_types=[".txt"])
    output = gr.Markdown(label="Assistant Report")

    analyze_button = gr.Button("Analyze Email Chain")
    clear_button = gr.ClearButton([email_file, output], value="Clear and Upload New File")

    analyze_button.click(fn=analyze_email, inputs=email_file, outputs=output)

app.launch()

