# -*- coding: utf-8 -*-
"""LAB 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cCF2epq31IU1r6jw-uNk8zmPlgU8ha9L
"""

#1. Install and configure Gemini API
!pip install -q -U google-genai
from google import genai
from google.genai import types
from getpass import getpass
import os
os.environ["GEMINI_API_KEY"] = getpass("Enter your Gemini API Key: ")
client = genai.Client()

def get_python_help(topic: str) -> str:
    print("Function called with topic:", topic)

    lessons = {
        "list comprehension": "Creates a list in one line, example: squares = [x*x for x in range(5)].",
        "list": "List stores multiple values, example: nums = [10, 20, 30].",
        "dictionary": "Dictionary stores key-value pairs, example: {'name': 'Ravi'}.",
        "for loop": "For loop repeats code, example: for i in range(3): print(i).",
        "if else": "if-else makes decisions, example: if marks >= 50: print('Pass').",
        "function": "Function is reusable code, example: def greet(): print('Hello')."
    }

    topic = topic.lower()

    for key, value in lessons.items():
        if key in topic:
            return value

    return "Tutorial not available. Available topics: " + ", ".join(lessons.keys())

def ask_python_tutor(question):
    prompt = f"""
Use the get_python_help tool to answer this beginner Python question.
Reply in one simple line only.
If the tool says "Tutorial not available", show the available topics also.
Question: {question}
"""
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(tools=[get_python_help])
    )
    return response.text

while True:
    user_question = input("Ask a Python syntax question: ")
    answer = ask_python_tutor(user_question)

    print("\nTutor Answer:\n")
    print(answer)
    choice = input("\n Would you like to continue with the next question? Type yes(y) or no(n): ")
    if choice.lower() != "y":
        print("\n Thank you for using the Python Syntax Tutor Agent.")
        break

